import Head from "next/head";
import { ItemsHome } from "@/components/ItemsHome/ItemsHome";
import { ItemsProvider } from "@/system/ItemsContext";
import { Header } from "@/components/Header/Header";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

export default function Home() {
  const queryClient = new QueryClient();
  return (
    <>
      <Head>
        <title>Coin List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <QueryClientProvider client={queryClient}>
        <ItemsProvider>
          <ItemsHome />
        </ItemsProvider>
      </QueryClientProvider>
    </>
  );
}
